---
title: "Economie Contemporaine"
always_allow_html: yes
bibliography: eco_generale.bib
citeproc: true
toc: true
code-fold: true
warning: false
code-summary: "Show the code"
theme: flatly
css: custom.css
editor: visual
format:
  html:
    theme: flatly
  beamer-pdf:
    theme: Madrid
    colortheme: dolphin
    toc: false
---

#### 1. Objectifs du cours

Développer la capacité d’analyse critique des étudiants sur les enjeux de croissance, d’emploi, de finances, de monnaie et de politiques publiques.

#### 2. Description du cours

Ce cours est complémentaire aux différents cours dispensés en L1 EG, il traite de l'actualité économique et présente les grands débats sur la croissance et l'emploi, sur les finances et la monnaie ainsi que sur les politiques publiques\
\

#### 3. Plan du cours

-   Grands principes de la science économique (rareté et allocation des ressources; arbitrages; approche positive et normative)

-   La croissance en débat

-   Éléments sur la dette publique

-   Chômage, Emploi et politiques publiques

-   Économie internationale

#### 4. Compétences visées

-   Interpréter des données et différents documents économiques

-   Construire et développer une argumentation avec esprit critique

#### 5. Modalités pédagogiques

**Mode d'enseignement :** Présentiel

**Langue(s) utilisée(s) :** français

**Méthodes pédagogiques :** Cours magistral, Exposé présenté par les étudiants

#### 6. Modalités d'évaluation

Examen écrit sur table

#### 7. Bibliographie

-   Questions économiques contemporaines, Guerrero N., 2013

-   DCG5: Économie contemporaine, Castaing S. ; Charles L.; Coquet J.; Kurowska C.

-   Economix: la première histoire de l'économie en BD (Goodwin M. )

-   Supports audio et vidéo :

    \- France Culture (l'économie en questions)

-   Presse:

-   Les Echos, Alternatives économiques, Courrier International
