---
title: ""
format: html
---

# Thèmes de Recherche

Economie et identité; Genre; Distances aux normes

# Travail en cours

Vers une mesure continue de l'identité de Genre: enjeux pour l'analyse économique

# Thèse

Thèse soutenue en 2015

"Essais sur la ségrégation et l'identité en France"

Sous la direction de Benoît Tarroux

Mention très honorable

Jury :

Prof. Catherine Baumont, Université de Bourgogne (Rapporteur)

Prof. Isabelle Lebon, Université de Caen (Présidente)

Prof. Yannick L’Horty, Université Paris-Est Marne la vallée (Rapporteur)

Prof. Fabien Moizeau, Université de Rennes 1 (Examinateur)

Benoît Tarroux, Université de Rennes 1 (Directeur)

# Encadrements :

Mémoire APEME : Femmes économistes: Oubliées de l'Histoire, Anaïs Bidau

# Communications

2024, Conférence AFEPOP, Aubervilliers, *"Beyond Binary: Continuous Measurement of Gender through Cultural Practices"*

2014 ESA, Experimental economics, european meeting, Prague

2012 Conférence Territoires, Emploi et Politiques Publiques (TEPP), Caen Séminaire doctoral de l'association PROJECT et du CREM (Centre de Recherche en Economie et Management), Rennes

2011 Journées Louis-André Gérard-Varet (LAGV), Marseille
